import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
// import styles from '../styles/Home.module.scss'

export default (() => {
	return (
		<div className="flex min-h-screen justify-center items-center">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="max-w-xs rounded overflow-hidden shadow-lg my-2">
				<Image
					layout="responsive"
					className="w-full"
					src="https://picsum.photos/1000/1000?random"
					width={'100%'}
					height={'100%'}
					alt="A random picture"
				/>
				<div className="px-6 py-4">
					<div className="font-bold text-xl mb-2">Next + Tailwind ❤️</div>
					<p className="text-grey-darker text-base">
						Next and Tailwind CSS are a match made in heaven, check out this
						article on how you can combine these two for your next app.
					</p>
				</div>
			</div>
		</div>
	)
}) as NextPage
